pip install Flask
pip install Flask-SQLAlchemy
pip install Flask-WTF
pip install Flask-Login
pip install Flask-Security
pip install twill
pip install simplejson
pip install Flask-Testing
pip install MySQL-python
pip install Flask-MySQL
pip install Flask-HTTPAuth
pip install Flask-PyMongo
pip install sqlparse
pip install xlwt
pip install CherryPy
